### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by zreisman** [gumroad/octopus#1]
Recent commit advises Octopus no longer be used for sharding.

**Comment by leighmcculloch** [comment]
@zreisman can you link to the commit? I can't see the commit in the parent repo that says sharding should be used any longer.

**Comment by zreisman** [comment]
https://github.com/gumroad/octopus/commit/32a6e3a87c7e81aa8a6d2e8d776d2eff84c7c25b

**Comment by leighmcculloch** [comment]
Thanks @zreisman. If you'd like to use octopus with sharding, please use https://github.com/tchandy/octopus which is the official release. This is a fork of this which some short term changes to make it work with the version of rails we're using. I'm closing this.
